version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
    image: frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped 