apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config

data:
  NODE_ENV: "production"
  API_URL: "http://backend-service:5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret

type: Opaque
stringData:
  API_KEY: "example-secret-key" 